/**
 * export.js
 * Converts a session (with enriched steps + screenshots) into various export formats.
 *
 * Supported formats:
 *  - "markdown"  → .md file, screenshots embedded as base64 or saved to a zip
 *  - "html"      → self-contained .html with inline screenshots
 *  - "intercom"  → Intercom Help Center Article JSON (ready for Articles API)
 *  - "json"      → Raw session JSON (for backup / import)
 *
 * Each format returns { filename, mimeType, content } where content is a string.
 * The service worker triggers a chrome.downloads.download for the user.
 */

import { db } from "./db.js";

export async function exportSession(session, format) {
  // Hydrate steps with screenshots for export
  const steps = await Promise.all(
    session.steps.map(async (step) => {
      const full = await db.getStep(step.id);
      return full || step;
    })
  );
  const hydratedSession = { ...session, steps };

  switch (format) {
    case "markdown":  return exportMarkdown(hydratedSession);
    case "html":      return exportHtml(hydratedSession);
    case "intercom":  return exportIntercom(hydratedSession);
    case "json":      return exportJson(hydratedSession);
    default:          throw new Error(`Unknown format: ${format}`);
  }
}

// ─── Markdown ─────────────────────────────────────────────────────────────────

function exportMarkdown(session) {
  const lines = [];
  lines.push(`# ${session.name}\n`);
  lines.push(`*Generated by Guidr · ${new Date().toLocaleDateString()}*\n`);

  for (const [i, step] of session.steps.entries()) {
    lines.push(`\n## Step ${i + 1}: ${step.title || "Untitled"}\n`);
    if (step.screenshotAfter || step.screenshotBefore) {
      const img = step.screenshotAfter || step.screenshotBefore;
      lines.push(`![Step ${i + 1} screenshot](${img})\n`);
    }
    if (step.body) lines.push(`${step.body}\n`);
    lines.push(`\n---`);
  }

  return {
    filename: `${slugify(session.name)}.md`,
    mimeType: "text/markdown",
    content: lines.join("\n"),
  };
}

// ─── HTML ─────────────────────────────────────────────────────────────────────

function exportHtml(session) {
  const stepsHtml = session.steps
    .map(
      (step, i) => `
    <article class="step">
      <div class="step-number">${i + 1}</div>
      <div class="step-content">
        <h2>${escHtml(step.title || "Untitled step")}</h2>
        <p>${escHtml(step.body || "")}</p>
        ${
          step.screenshotAfter || step.screenshotBefore
            ? `<img src="${step.screenshotAfter || step.screenshotBefore}" alt="Step ${i + 1}" loading="lazy"/>`
            : ""
        }
      </div>
    </article>`
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${escHtml(session.name)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           line-height: 1.6; color: #1a1a1a; background: #fafafa; padding: 2rem; }
    .guide { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    .meta { color: #666; font-size: 0.875rem; margin-bottom: 2.5rem; }
    .step { display: flex; gap: 1.5rem; margin-bottom: 2.5rem;
            background: #fff; border-radius: 12px; padding: 1.5rem;
            box-shadow: 0 1px 4px rgba(0,0,0,.08); }
    .step-number { flex-shrink: 0; width: 36px; height: 36px; border-radius: 50%;
                   background: #6366f1; color: #fff; font-weight: 700;
                   display: flex; align-items: center; justify-content: center; }
    .step-content h2 { font-size: 1.125rem; margin-bottom: 0.5rem; }
    .step-content p { color: #444; margin-bottom: 1rem; }
    .step-content img { width: 100%; border-radius: 8px; border: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="guide">
    <h1>${escHtml(session.name)}</h1>
    <p class="meta">Generated by Guidr · ${new Date().toLocaleDateString()}</p>
    ${stepsHtml}
  </div>
</body>
</html>`;

  return {
    filename: `${slugify(session.name)}.html`,
    mimeType: "text/html",
    content: html,
  };
}

// ─── Intercom Articles API ────────────────────────────────────────────────────
/**
 * Intercom Help Center Articles accept HTML body content via their REST API.
 * https://developers.intercom.com/docs/references/rest-api/api.intercom.io/Articles/article/
 *
 * This export produces JSON you paste into a POST /articles request,
 * or can wire up directly with an Intercom API key in the options page.
 *
 * Notes:
 *  - Intercom doesn't support embedded base64 images in article HTML.
 *    Screenshots are omitted from the body — add image hosting in v2.
 *  - The `author_id` field must be filled by the user (their Intercom admin ID).
 */
function exportIntercom(session) {
  const bodyHtml = session.steps
    .map(
      (step, i) => `
<h2>${i + 1}. ${escHtml(step.title || "Untitled step")}</h2>
<p>${escHtml(step.body || "")}</p>`
    )
    .join("\n");

  const article = {
    title: session.name,
    body: bodyHtml.trim(),
    state: "draft", // "published" to go live immediately
    parent_type: "collection", // or "section"
    // The two nulls below are placeholders the end user fills in before POSTing
    // to the Intercom Articles API. See README → "Intercom Article JSON".
    parent_id: null,
    author_id: null,
    // Intercom-specific metadata
    _guidr_meta: {
      exportedAt: new Date().toISOString(),
      sessionId: session.id,
      stepCount: session.steps.length,
    },
  };

  return {
    filename: `${slugify(session.name)}-intercom.json`,
    mimeType: "application/json",
    content: JSON.stringify(article, null, 2),
  };
}

// ─── Raw JSON (backup / import) ───────────────────────────────────────────────

function exportJson(session) {
  // Strip screenshot blobs to keep file size manageable — screenshots are large
  const slim = {
    ...session,
    steps: session.steps.map(({ screenshotBefore, screenshotAfter, ...rest }) => rest),
    _guidr_export: { version: "0.1", exportedAt: new Date().toISOString() },
  };
  return {
    filename: `${slugify(session.name)}-backup.json`,
    mimeType: "application/json",
    content: JSON.stringify(slim, null, 2),
  };
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function slugify(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function escHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
